package game;

public enum GameAction {
  PLAYER1_N,
  PLAYER1_NE,
  PLAYER1_E,
  PLAYER1_SE,
  PLAYER1_S,
  PLAYER1_SW,
  PLAYER1_W,
  PLAYER1_NW,
  PLAYER1_STOP,
  PLAYER1_PURCHASE_MARINE,
  PLAYER1_PURCHASE_SNIPER,
  PLAYER1_PURCHASE_ROGUE,

  PLAYER2_N,
  PLAYER2_NE,
  PLAYER2_E,
  PLAYER2_SE,
  PLAYER2_S,
  PLAYER2_SW,
  PLAYER2_W,
  PLAYER2_NW,
  PLAYER2_STOP,
  PLAYER2_PURCHASE_MARINE,
  PLAYER2_PURCHASE_SNIPER,
  PLAYER2_PURCHASE_ROGUE;
}
